spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8082

spring.application.name: user-service
